#!/bin/sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
nvm use default > /dev/null

echo "🔍 Linting and formatting staged files..."
npx lint-staged

# echo "🧪 Running tests..."
# npx vitest run
